version: "3.0"

services:
  app:
    image: franciscogsilverio/nest-cloud-run:latest
    container_name: api
    networks:
      - node-network
    tty: true
    ports:
      - "3000:3000"
    command: "node dist/main.js"

  nginx:
    image: franciscogsilverio/fetin-credit-control-nginx:latest
    container_name: nginx
    restart: always
    networks:
      - node-network
    ports:
      - "8080:80"

networks:
  node-network:
    driver: bridge
