version: "3.0"

services:
  app:
    image: franciscogsilverio/nest-cloud-run:latest
    container_name: api
    networks:
      - node-network
    tty: true
    command: "node dist/main.js"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    networks:
      - node-network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    tty: true

networks:
  node-network:
    driver: bridge
